FROM ubuntu:latest

# Copy your monitoring system to container
ADD <YOUR PROGRAM> /usr/bin/qlnetstats

# Add crontab file in the cron directory
ADD crontab /etc/cron.d/network-monit

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/network-monit

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

#Install Cron
RUN apt-get update
RUN apt-get -y install cron iputils-ping

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log